# Generated by Django 3.0.2 on 2020-01-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_documentos_mi_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mi_documento',
            old_name='comunicado',
            new_name='documento',
        ),
    ]
