# Generated by Django 3.0.2 on 2020-01-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200122_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mi_documento_enviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Documentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuarios')),
            ],
        ),
    ]
